# Generated by Django 6.0 on 2026-01-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phno', models.IntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='myapp',
        ),
    ]
